name: Label PR with Areas

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read # minimum permission to checkout the repo such that .areas can be parsed.

jobs:
  label-pr:
    runs-on: ubuntu-latest
    environment: pr-workflows
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          # The action only needs access to the .areas configuration,
          # but the workflows in this repo use the compiled action directly, so it also needs dist/index.js
          sparse-checkout: |
            .areas
            dist/index.js

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ vars.CODE_AREAS_APP_ID }}
          private-key: ${{ secrets.CODE_AREAS_PEM }}

      - name: Label PR
        uses: ./
        with:
          token: ${{ steps.generate-token.outputs.token }}
          command: label-pr
