name: Update Area Rulesets

on:
  push:
    branches:
      - main
    paths:
      - '.areas/**'
      - '.github/workflows/areas-ruleset-sync.yml'
      - 'action.yml'
      - 'dist/index.js'

permissions:
  contents: read

jobs:
  manage-areas:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Sync Area Rulesets
        uses: ./
        with:
          token: ${{ secrets.DEV_TOKEN }}
          command: ruleset-sync
